import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";

const migrationPath = resolve(
  process.cwd(),
  "supabase/migrations/202608240001_telegram_private_inbox.sql",
);

test("Telegram intake is private, account-scoped and does not auto-publish", () => {
  const source = readFileSync(migrationPath, "utf8");

  assert.match(source, /create table if not exists public\.telegram_account_links/i);
  assert.match(source, /create table if not exists public\.telegram_intakes/i);
  assert.match(source, /create table if not exists public\.telegram_saved_notes/i);
  assert.match(source, /create table if not exists public\.telegram_zagulyaky_draft_origins/i);
  assert.match(source, /create table if not exists public\.telegram_zagulyaky_candidates/i);
  assert.match(source, /alter table public\.telegram_intakes enable row level security/i);
  assert.match(source, /revoke all on table public\.telegram_intakes from public, anon, authenticated/i);
  assert.match(source, /candidate_kind, 'draft', 'unverified'/i, "AI output must remain a private draft");
  assert.doesNotMatch(source, /status = 'published'/i, "Telegram worker must never publish a catalogue record");
  assert.doesNotMatch(source, /submit_zagulyaka_v1/i, "Telegram worker must never submit a draft for moderation");
});

test("Telegram intake uses a one-time code, service-only queue and fenced normal private draft attachments", () => {
  const source = readFileSync(migrationPath, "utf8");

  assert.match(source, /token_hash text not null unique/i);
  assert.match(source, /telegram_link_tokens_one_active_owner_idx/i);
  assert.match(source, /security_private\.telegram_sha256_v1\(link_code\)/i);
  assert.match(source, /for update skip locked/i);
  assert.match(source, /zagulyaky-private/i);
  assert.doesNotMatch(source, /telegram-intake-private/i, "Do not create an orphan-prone second Storage bucket");
  assert.match(source, /create table if not exists public\.telegram_intake_media_attachments/i);
  assert.match(source, /create table if not exists public\.telegram_media_upload_fences/i);
  assert.match(source, /reservation_token uuid not null/i);
  assert.match(source, /upload_lease_expires_at timestamptz not null/i);
  assert.match(source, /service_reserve_telegram_media_attachment_v1/i);
  assert.match(source, /service_renew_telegram_intake_lease_v1/i);
  assert.match(source, /where status in \('processing', 'materialized'\)/i);
  assert.match(source, /enqueue_telegram_pending_attachment_cleanup_v1/i);
  assert.match(source, /service_claim_telegram_media_cleanup_v1/i);
  assert.match(source, /service_finalize_telegram_media_cleanup_v1/i);
  assert.match(source, /service_attach_telegram_media_to_zagulyaka_v1/i);
  assert.match(source, /service_finalize_telegram_zagulyaka_v1/i);
  assert.match(source, /grant execute on function public\.service_claim_telegram_intake_v1\(text,integer\) to service_role/i);
  assert.match(source, /revoke all on function public\.service_claim_telegram_intake_v1\(text,integer\) from public, anon, authenticated/i);
  assert.match(source, /active_intent = 'zagulyaka' and not link_row\.ai_opt_in/i);
  assert.match(source, /TELEGRAM_AI_PERMISSION_REVOKED/i);
  assert.match(source, /candidate_source_url/i);
  assert.match(source, /Надіслано через приватний Telegram-бот/i);
  assert.match(source, /before delete on public\.profiles/i);
  assert.match(source, /delete_private_telegram_drafts_on_profile_delete_v1/i);
  assert.match(source, /record_row\.status <> 'published'/i);
  assert.match(source, /telegram_zagulyaky_draft_origins origin/i);
  assert.match(source, /delete from public\.telegram_zagulyaky_draft_origins\s+where owner_id = old\.user_id/i);
  assert.match(source, /upload_lease_expires_at \+ interval '60 seconds'/i);
  assert.match(source, /p_reservation_token uuid/i);
  assert.doesNotMatch(
    source,
    /service_reserve_telegram_media_attachment_v1\(\s*p_intake_id uuid, p_claim_token uuid, p_media_id uuid, p_record_id uuid,\s*p_storage_path/s,
    "Storage paths must be generated by the database reservation, never supplied by the worker",
  );
});

test("Telegram functions are present as separate webhook and worker boundaries", () => {
  const webhook = resolve(process.cwd(), "supabase/functions/telegram-webhook/index.ts");
  const worker = resolve(process.cwd(), "supabase/functions/process-telegram-inbox/index.ts");

  assert.ok(existsSync(webhook), "Expected a narrow Telegram webhook entrypoint");
  assert.ok(existsSync(worker), "Expected a separate Telegram queue worker");
  const webhookSource = readFileSync(webhook, "utf8");
  const workerSource = readFileSync(worker, "utf8");
  assert.match(webhookSource, /X-Telegram-Bot-Api-Secret-Token/i);
  assert.match(webhookSource, /constantTimeEqual/i);
  assert.match(webhookSource, /chat\.type !== "private"/i);
  assert.match(workerSource, /service_attach_telegram_media_to_zagulyaka_v1/i);
  assert.match(workerSource, /service_reserve_telegram_media_attachment_v1/i);
  assert.match(workerSource, /p_reservation_token: reservation\.reservationToken/i);
  assert.match(workerSource, /storage\/v1\/object/i);
  assert.match(workerSource, /AbortController/i);
  assert.match(workerSource, /service_claim_telegram_media_cleanup_v1/i);
  assert.match(workerSource, /service_finalize_telegram_media_cleanup_v1/i);
  assert.match(workerSource, /await renewIntakeLease\(client, task\)/i);
  assert.match(workerSource, /service_finalize_telegram_zagulyaka_v1/i);
  assert.match(workerSource, /conservativeLargePhotoCandidate/i);
  assert.match(workerSource, /sourceUrl: source\?\.url/i);
  assert.doesNotMatch(webhookSource, /console\.log\(/i);
  assert.doesNotMatch(workerSource, /console\.log\(/i);
});

test("forwarded Telegram posts retain only safe, private note provenance", () => {
  const webhook = resolve(process.cwd(), "supabase/functions/telegram-webhook/index.ts");
  const worker = resolve(process.cwd(), "supabase/functions/process-telegram-inbox/index.ts");
  const migration = readFileSync(migrationPath, "utf8");
  const webhookSource = readFileSync(webhook, "utf8");
  const workerSource = readFileSync(worker, "utf8");

  // A channel post is forwarded *to the user's private bot chat*; the bot is
  // never made a member of the source channel/group. New Bot API metadata is
  // preferred, with a narrow legacy compatibility fallback.
  assert.match(webhookSource, /chat\.type !== "private"/i);
  assert.match(webhookSource, /forward_origin/i);
  assert.match(webhookSource, /forward_from_chat/i);
  assert.match(webhookSource, /forwardSource:\s*forwardedSource\(message\)/i);
  assert.match(webhookSource, /p_source_metadata:\s*message\.forwardSource \?\? \{\}/i);
  assert.match(webhookSource, /typeof message\.text === "string"[\s\S]{0,180}typeof message\.caption === "string"/i);

  // Only a public channel username plus Telegram's original message ID may
  // become a permalink. There must be no fabricated /c/ (private chat) link.
  assert.match(webhookSource, /originType === "channel"/i);
  assert.match(webhookSource, /https:\/\/t\.me\/\$\{username\}\/\$\{messageId\}/i);
  assert.match(webhookSource, /Do not derive the \/c\/ form/i);
  assert.match(webhookSource, /originType: "hidden_user"[\s\S]{0,700}?publicPermalink: null/i);

  assert.match(migration, /source_metadata jsonb not null default '\{\}'::jsonb/i);
  assert.match(migration, /source_label text check \(source_label is null or char_length\(source_label\) between 1 and 300\)/i);
  assert.match(migration, /create or replace function security_private\.telegram_source_metadata_v1\(p_value jsonb\)/i);
  assert.match(migration, /p_source_metadata jsonb default '\{\}'::jsonb/i);
  assert.match(migration, /'publicPermalink', nullif\(public_permalink_value, ''\)/i);
  assert.match(migration, /'originalPlatform', 'telegram'/i);
  assert.match(migration, /'originType', nullif\(origin_type_value, ''\)/i);
  assert.match(migration, /public_permalink_value !~\* '\^https:\/\/t\[\.\]me\//i);

  // The worker must turn the normalized forwarding metadata into the note's
  // own provenance. A public forwarded Telegram permalink takes precedence
  // over an outbound link inside that forwarded post.
  assert.match(workerSource, /sourceMetadata/i);
  assert.match(workerSource, /publicPermalink/i);
  assert.match(workerSource, /p_source_label:/i);
  assert.match(workerSource, /p_source_metadata:/i);
  assert.match(workerSource, /platform:\s*"telegram"/i);

  // Captioned forwarded photos remain bookmark-sized: retain their caption
  // and provenance, but never create generic note media. A photo-only forward
  // or a normal photo note still requires the explicit Zagulyaka flow.
  assert.match(
    migration,
    /if active_intent = 'note' and p_media is not null then[\s\S]{0,700}normalized_text <> '' and coalesce\(\(normalized_source_metadata ->> 'forwarded'\)::boolean, false\)/i,
  );
  assert.match(migration, /'mediaOmitted', media_omitted/i);
  assert.match(migration, /'reason', 'photo_requires_zagulyaka'/i);
  assert.match(webhookSource, /result\.mediaOmitted === true/i);
});

test("a directly shared Facebook link remains a private Facebook note", () => {
  const worker = readFileSync(
    resolve(process.cwd(), "supabase/functions/process-telegram-inbox/index.ts"),
    "utf8",
  );

  // Facebook URLs are accepted only as sanitized HTTPS/HTTP source addresses;
  // their text remains the note body and the worker does not fetch or publish
  // the original post.
  assert.match(worker, /host === "facebook\.com" \|\| host\.endsWith\("\.facebook\.com"\)/i);
  assert.match(worker, /host === "fb\.com" \|\| host\.endsWith\("\.fb\.com"\) \|\| host === "fb\.watch"/i);
  assert.match(worker, /\? "facebook"/i);
  assert.match(worker, /p_source_url:/i);
  assert.match(worker, /p_source_platform:/i);
  assert.doesNotMatch(worker, /fetch\([^\n]*facebook/i);
});

test("Telegram queue is scheduled independently from the generic reminder worker", () => {
  const workflow = resolve(process.cwd(), ".github/workflows/telegram-inbox.yml");
  assert.ok(existsSync(workflow), "Expected a dedicated Telegram inbox schedule");
  const source = readFileSync(workflow, "utf8");

  assert.match(source, /cron: "\*\/5 \* \* \* \*"/);
  assert.match(source, /TELEGRAM_WORKER_SECRET/);
  assert.match(source, /process-telegram-inbox/);
  assert.doesNotMatch(source, /TASK_REMINDER_CRON_SECRET/);
});
