// Generated by scripts/generate-public-seo.mjs. Keep article bodies out of the app bundle.
export const publicResearchLinks = [
  {
    "slug": "posibnyk-z-henealohii",
    "heading": "Посібник для самостійного дослідження родоводу",
    "summary": "Авторський посібник Андрія Каленського: п’ять етапів дослідження та повний PDF для читання."
  },
  {
    "slug": "rodove-derevo-onlain",
    "heading": "Як створити родове дерево онлайн українською",
    "summary": "Почніть із близьких, додайте родинні зв’язки та зберіть історію сім’ї в одному дереві."
  },
  {
    "slug": "poshuk-predkiv",
    "heading": "Як знайти своїх предків: із чого почати пошук",
    "summary": "Дізнайтеся, як перейти від прізвища та сімейних спогадів до перевірених відомостей про предків."
  },
  {
    "slug": "arkhivni-dokumenty",
    "heading": "Архівні документи для дослідження родоводу",
    "summary": "Зберігайте скани, архівні реквізити й висновки так, щоб кожен факт можна було перевірити."
  }
];
